name: NekoEvent
main: jp.kentan.minecraft.neko_event.NekoEvent
version: 2.0.0
author: ken_kentan
website: http://ken.kentan.jp
softdepend: [Multiverse-Core]

commands:
    event:
        description: NekoEvent
        usage: /<command>
        permission: neko.event
        permission-message: You don't have <permission>
    gacha:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.gacha
        permission-message: You don't have <permission>
    dungeon:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.dungeon
        permission-message: You don't have <permission>
    parkour:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.parkour
        permission-message: You don't have <permission>
    key:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.key
        permission-message: You don't have <permission>
    password:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.password
        permission-message: You don't have <permission>
