name: NekoEvent
main: jp.kentan.minecraft.event.NekoEvent
version: 1.10.15
author: ken_kentan
website: http://ken.kentan.jp

commands:
    event:
        description: NekoEvent
        usage: /<command>
        permission: jp.kentan.minecraft.event
        permission-message: You don't have <permission>
