name: NekoEvent
main: jp.kentan.minecraft.nekoevent.NekoEvent
version: 3.0.0
author: ken_kentan
website: http://ken.kentan.jp
softdepend: [Multiverse-Core]

commands:
    gacha:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.gacha
        permission-message: You don't have <permission>
    key:
        description: NekoEvent
        usage: /<command>
        permission: neko.event.key
        permission-message: You don't have <permission>